export const NIGERIAN_BANKS = [
  { label: "Access Bank", value: "ACCESS" },
  { label: "Citibank", value: "CITIBANK" },
  { label: "Ecobank", value: "ECOBANK" },
  { label: "Fidelity Bank", value: "FIDELITY" },
  { label: "First Bank", value: "FIRSTBANK" },
  { label: "First City Monument Bank (FCMB)", value: "FCMB" },
  { label: "Globus Bank", value: "GLOBUS" },
  { label: "Guaranty Trust Bank (GTBank)", value: "GTBANK" },
  { label: "Heritage Bank", value: "HERITAGE" },
  { label: "Jaiz Bank", value: "JAIZ" },
  { label: "Keystone Bank", value: "KEYSTONE" },
  { label: "Kuda Bank", value: "KUDA" },
  { label: "Lotus Bank", value: "LOTUS" },
  { label: "Opay", value: "OPAY" },
  { label: "Palmpay", value: "PALMPAY" },
  { label: "Parallex Bank", value: "PARALLEX" },
  { label: "Polaris Bank", value: "POLARIS" },
  { label: "Providus Bank", value: "PROVIDUS" },
  { label: "Stanbic IBTC Bank", value: "STANBIC" },
  { label: "Standard Chartered Bank", value: "STANDARD_CHARTERED" },
  { label: "Sterling Bank", value: "STERLING" },
  { label: "Suntrust Bank", value: "SUNTRUST" },
  { label: "Titan Trust Bank", value: "TITAN" },
  { label: "Union Bank", value: "UNION" },
  { label: "United Bank for Africa (UBA)", value: "UBA" },
  { label: "Unity Bank", value: "UNITY" },
  { label: "Wema Bank", value: "WEMA" },
  { label: "Zenith Bank", value: "ZENITH" },
];
