import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import poppins from "@/config/font";
import { Providers } from "./providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "SISSL",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${poppins.variable} font-poppins antialiased dark`}
            >
                <Providers>
                    <Suspense>{children}</Suspense>
                    <Toaster position="top-center" theme="dark" />
                </Providers>
            </body>
        </html>
    );
}
