import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/modules/website/Navbar";
import Footer from "@/modules/website/Footer";

export const metadata: Metadata = {
    title: "SISSL",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            {children}
            <Footer />
        </>
    );
}
